---

- hosts: webserver
  serial: 1

  tasks:
  - name: take out of load balancer pool
    command: touch {{ inventory_hostname }}
    delegate_to: 127.0.0.1

  - name: actual steps would go here
    yum: name=vim state=present
