---
- hosts: webserver
  tasks:
    - block:
      - dnf: name={{ item }} state=installed
        with_items:
        - httpd

      - service: name=httpd state=started enabled=True

      when: ansible_distribution == 'CentOS'
...
